(function(){
  const dict = {
    vi: {
      login_brand_title: 'Nền tảng học prompt gọn, rõ, hiệu quả.',
      login_hero_copy: 'Dành cho học sinh và người dùng muốn viết prompt tốt hơn, học nhanh hơn và làm việc mạch lạc hơn.',
      demo_account_label: 'Tài khoản demo',
      login_benefit_1: 'Đăng nhập giả lập bằng JavaScript phía client.',
      login_benefit_2: 'Lưu hồ sơ demo cho phần Settings và Tools.',
      login_benefit_3: 'Tối ưu cho học tập, thử prompt và làm việc hằng ngày.',
      tab_login: 'Đăng nhập',
      tab_register: 'Đăng ký',
      login_title: 'Chào mừng trở lại',
      login_subtitle: 'Đăng nhập để tiếp tục vào không gian học tập và công cụ prompt.',
      label_email: 'Email',
      label_password: 'Mật khẩu',
      remember_me: 'Ghi nhớ phiên demo',
      forgot_password: 'Quên mật khẩu?',
      btn_login: 'Đăng nhập',
      or_continue: 'Hoặc tiếp tục với',
      login_note: 'Mẫu demo chạy hoàn toàn ở phía trình duyệt, không cần backend thật.',
      register_title: 'Tạo tài khoản demo',
      register_subtitle: 'Nhập thông tin để hệ thống dùng lại trong Settings.',
      label_full_name: 'Họ và tên',
      label_phone: 'Số điện thoại',
      label_class: 'Lớp học',
      label_role: 'Vai trò',
      label_purpose: 'Mục đích sử dụng',
      role_student: 'Học sinh',
      role_teacher: 'Giáo viên',
      role_self: 'Tự học',
      label_password_confirm: 'Xác nhận mật khẩu',
      accept_terms: 'Tôi đồng ý sử dụng bản demo cho mục đích học tập.',
      btn_create_account: 'Tạo tài khoản',
      register_note: 'Sau khi đăng ký, hệ thống sẽ chuyển vào trang chính với loading 1 giây.',
      home_note_title: 'Tập trung vào nội dung giới thiệu rõ ràng.',
      home_note_desc: 'Home được giữ gọn hơn để làm đúng nhiệm vụ chính: giới thiệu sản phẩm, định hướng sử dụng và dẫn người dùng sang các trang chức năng.',
      home_metric_tools: 'Công cụ riêng',
      home_metric_lang: 'Ngôn ngữ',
      home_metric_flow: 'Luồng demo',
      home_input_tag: 'Khung nhập nội dung',
      home_input_title: 'Ghi nhanh nội dung, câu hỏi hoặc dàn ý trước khi chuyển sang Tools.',
      home_input_desc: 'Khung này giúp trang chủ có một điểm nhập liệu rõ ràng, phù hợp với luồng học tập và viết prompt.',
      home_input_label: 'Nội dung cần xử lý',
      home_input_hint: 'Mẫu nháp',
      home_input_btn: 'Chuyển sang Tools',
      loading_title: 'Đang chuẩn bị không gian của bạn',
      loading_subtitle: 'Vui lòng đợi trong giây lát…',
      forgot_title: 'Khôi phục mật khẩu',
      forgot_desc: 'Nhập email demo để nhận thông báo giả lập. Không có email thật được gửi đi.',
      btn_send_link: 'Gửi liên kết khôi phục',
      home_tag: 'Nền tảng học tập & prompt lab',
      home_hero_title: 'Viết prompt tốt hơn, học tập nhanh hơn, làm việc rõ ràng hơn.',
      home_hero_desc: 'PromptPilot là không gian demo được thiết kế như một sản phẩm thật: có đăng nhập giả lập, công cụ tạo prompt riêng, cài đặt hồ sơ và điều hướng rõ ràng.',
      home_cta_tools: 'Mở Tools',
      home_cta_settings: 'Mở Settings',
      spotlight_title: 'Tập trung vào tính hữu dụng',
      spotlight_desc: 'Mọi thành phần đều hướng tới việc học prompt dễ hơn, rõ hơn và có thể dùng lại ngay.',
      stat_tools: 'Công cụ chính',
      stat_langs: 'Ngôn ngữ giao diện',
      stat_flow: 'Luồng demo gọn',
      home_content_tag: 'Nội dung',
      home_content_title: 'Bố cục rõ ràng, dễ đọc, không gây rối.',
      content_card_1_title: 'Đăng nhập / đăng ký giả lập',
      content_card_1_desc: 'Toàn bộ logic chạy bằng JavaScript phía client, đủ cho demo học tập và thử nghiệm.',
      content_card_2_title: 'Quản lý thông tin người dùng',
      content_card_2_desc: 'Dữ liệu nhập ở form được lưu lại để Settings hiển thị và chỉnh sửa.',
      content_card_3_title: 'Prompt output có thể copy',
      content_card_3_desc: 'Kết quả được trình bày sạch, đẹp, có nút copy và sẵn sàng dùng lại.',
      home_tools_tag: 'Công cụ',
      home_tools_title: 'Ba công cụ prompt cho học tập, code và công việc.',
      home_tools_link: 'Đi tới Tools',
      mini_tool_1_title: 'Prompt học tập',
      mini_tool_1_desc: 'Tạo prompt theo môn học, lớp và mục tiêu đầu ra.',
      mini_tool_2_title: 'Prompt viết code',
      mini_tool_2_desc: 'Gọn, rõ và hiệu quả cho các yêu cầu lập trình thực tế.',
      mini_tool_3_title: 'Prompt công việc',
      mini_tool_3_desc: 'Phục vụ task, planning, note-taking và quản trị thời gian.',
      home_settings_tag: 'Cài đặt',
      home_settings_title: 'Hồ sơ demo, ngôn ngữ và tùy chỉnh cá nhân.',
      home_settings_link: 'Mở Settings',
      settings_preview_label: 'Dữ liệu sẽ đồng bộ từ trang đăng nhập',
      settings_preview_pill: 'Sửa được trong giao diện demo',
      home_contact_tag: 'Liên hệ',
      home_contact_title: 'Khu vực kết nối gọn gàng, sẵn sàng thay link sau.',
      home_contact_link: 'Mở Contact',
      contact_spot_title: 'Mạng xã hội',
      contact_spot_desc: 'Các đường dẫn đều là placeholder, bạn có thể chèn link thật sau.',
      contact_spot_title_2: 'Hỗ trợ học tập',
      contact_spot_desc_2: 'Thiết kế tối ưu cho học sinh, người tự học và nhóm làm việc nhỏ.',
      chat_tag: 'Mini chatbot',
      chat_title: 'Hỏi nhanh về website ngay trong trang chủ.',
      tools_tag: 'Tools',
      tools_title: 'Bộ tạo prompt thực dụng cho học tập, code và công việc.',
      tools_desc: 'Mỗi công cụ dùng preset riêng để tạo đầu ra rõ, ngắn gọn và dùng được ngay.',
      tool1_title: 'Tạo prompt học tập',
      tool1_subtitle: 'Môn học, lớp, câu hỏi và đầu ra mong muốn.',
      label_subject: 'Môn học',
      label_question: 'Câu hỏi muốn hỏi',
      label_output: 'Đầu ra mong muốn',
      btn_generate_prompt: 'Tạo prompt',
      prompt_result: 'Prompt hoàn chỉnh',
      btn_copy: 'Copy',
      tool2_title: 'Tạo prompt viết code',
      tool2_subtitle: 'Mục tiêu, ngôn ngữ, kiểu project và yêu cầu đặc biệt.',
      label_language: 'Ngôn ngữ',
      label_project_type: 'Kiểu project',
      label_goal: 'Mục tiêu code',
      label_special: 'Yêu cầu đặc biệt',
      tool3_title: 'Tạo prompt công việc',
      tool3_subtitle: 'Task, planning, ghi chú và quản lý ưu tiên.',
      label_task: 'Mô tả nhiệm vụ',
      label_deadline: 'Deadline / thời gian',
      label_output_type: 'Kiểu đầu ra',
      settings_tag: 'Settings',
      settings_title: 'Quản lý hồ sơ demo và ngôn ngữ giao diện.',
      settings_desc: 'Thông tin được lấy từ đăng nhập/đăng ký và có thể chỉnh lại ngay trong giao diện.',
      edit_profile_title: 'Chỉnh sửa thông tin cá nhân',
      status_ready: 'Sẵn sàng',
      btn_save_changes: 'Lưu thay đổi',
      language_title: 'Ngôn ngữ',
      language_desc: 'Đổi ngôn ngữ chính của giao diện demo.',
      theme_title: 'Giao diện',
      theme_desc: 'Chọn chế độ sáng hoặc tối. Dark mode được cân bằng để dễ nhìn và không chói mắt.',
      theme_light: 'Light mode',
      theme_dark: 'Dark mode',
      contact_tag: 'Contact',
      contact_title: 'Khu vực liên hệ được bố cục rõ ràng, sẵn sàng chèn link thật.',
      contact_desc: 'Thiết kế tập trung vào sự gọn gàng, tin cậy và đủ khoảng trắng để nhìn dễ chịu.',
      contact_links_title: 'Liên kết nhanh',
      contact_info_title: 'Thông tin hỗ trợ',
      contact_hours: 'Giờ phản hồi',
      contact_cta_title: 'Một trang liên hệ chuyên nghiệp, không để trống trải.',
      contact_cta_desc: 'Bạn có thể thay phần link mạng xã hội bằng các đường dẫn thật sau khi triển khai.',
      contact_cta_button: 'Xem hồ sơ',
      contact_cta_button2: 'Mở công cụ',
      logout_title: 'Đăng xuất',
      logout_desc: 'Thoát khỏi phiên demo và quay về màn hình đăng nhập.',
      btn_logout: 'Đăng xuất',
      purpose_optional_note: 'có thể bỏ qua',
      login_unknown_account: 'Tài khoản này chưa được đăng kí , vui lòng đăng kí để tiếp tục',
      login_wrong_password: 'Mật khẩu chưa đúng.',
      home_story_pill: 'Khối văn bản chính',
      home_story_status: 'Dành cho nội dung giới thiệu',
      home_story_title: 'Đây là nơi bạn có thể bổ sung nội dung hiển thị của website.',
      home_story_desc: 'Khối này không phải ô nhập liệu. Nó được thiết kế như một khu vực trình bày văn bản tĩnh, giúp trang chủ giữ đúng vai trò giới thiệu sản phẩm, truyền tải định hướng sử dụng và tạo cảm giác có chiều sâu như một web thật.',
      home_story_quote: 'Nội dung rõ ràng giúp người dùng hiểu nhanh: website dùng để làm gì, đi tiếp ở đâu và công cụ nào đáng thử trước.',
      home_card_1_title: 'Đăng nhập / đăng ký giả lập',
      home_card_1_desc: 'Luồng client-side đủ thật để học tập và thử nghiệm, không cần backend.',
      home_card_2_title: 'Dữ liệu người dùng đồng bộ',
      home_card_2_desc: 'Thông tin từ đăng ký được giữ lại trong Settings để xem và chỉnh sửa.',
      home_card_3_title: 'Điều hướng rõ ràng',
      home_card_3_desc: 'Header và footer dẫn tới các trang chức năng riêng, không dồn tất cả vào một chỗ.',
      settings_avatar_title: 'Ảnh đại diện',
      settings_avatar_desc: 'Tải ảnh của bạn lên để dùng làm avatar trong hồ sơ góc trên bên phải.',
      settings_avatar_button: 'Tải ảnh lên',
      settings_avatar_remove: 'Xóa ảnh',
      settings_avatar_note: 'Nếu chưa có ảnh, hệ thống sẽ dùng avatar chữ viết tắt thay thế.'
    },
    en: {
      login_brand_title: 'A clean, practical prompt-learning platform.',
      login_hero_copy: 'Built for students and users who want better prompts, faster learning, and clearer workflows.',
      demo_account_label: 'Demo account',
      login_benefit_1: 'Client-side fake login powered by JavaScript.',
      login_benefit_2: 'Saves demo profile data for Settings and Tools.',
      login_benefit_3: 'Optimized for learning, prompt testing, and daily work.',
      tab_login: 'Login',
      tab_register: 'Register',
      login_title: 'Welcome back',
      login_subtitle: 'Sign in to continue into the learning workspace and prompt tools.',
      label_email: 'Email',
      label_password: 'Password',
      remember_me: 'Remember demo session',
      forgot_password: 'Forgot password?',
      btn_login: 'Log in',
      or_continue: 'Or continue with',
      login_note: 'This demo runs fully in the browser without a real backend.',
      register_title: 'Create demo account',
      register_subtitle: 'Enter details that will be reused in Settings.',
      label_full_name: 'Full name',
      label_phone: 'Phone number',
      label_class: 'Class',
      label_role: 'Role',
      label_purpose: 'Usage purpose',
      role_student: 'Student',
      role_teacher: 'Teacher',
      role_self: 'Self-learning',
      label_password_confirm: 'Confirm password',
      accept_terms: 'I agree to use this demo for learning purposes.',
      btn_create_account: 'Create account',
      register_note: 'After registration, the app will move to the main page with a 1-second loading screen.',
      home_note_title: 'Focused on clear introductory content.',
      home_note_desc: 'The homepage is intentionally minimal so it can introduce the product, guide usage, and direct users to the functional pages.',
      home_metric_tools: 'Dedicated tools',
      home_metric_lang: 'Languages',
      home_metric_flow: 'Demo flow',
      home_input_tag: 'Content input box',
      home_input_title: 'Quickly draft content, questions, or an outline before moving to Tools.',
      home_input_desc: 'This gives the homepage a clear input spot that fits the learning and prompt-writing flow.',
      home_input_label: 'Content to process',
      home_input_hint: 'Draft mode',
      home_input_btn: 'Go to Tools',
      loading_title: 'Preparing your workspace',
      loading_subtitle: 'Please wait a moment…',
      forgot_title: 'Password recovery',
      forgot_desc: 'Enter the demo email to see a simulated reset flow. No real email will be sent.',
      btn_send_link: 'Send recovery link',
      home_tag: 'Learning platform & prompt lab',
      home_hero_title: 'Write better prompts, learn faster, and work more clearly.',
      home_hero_desc: 'PromptPilot is a demo workspace designed like a real product: fake login, dedicated prompt generators, profile settings, and clear navigation.',
      home_cta_tools: 'Open Tools',
      home_cta_settings: 'Open Settings',
      spotlight_title: 'Focused on usefulness',
      spotlight_desc: 'Every element is designed to make prompt learning easier, clearer, and reusable right away.',
      stat_tools: 'Core tools',
      stat_langs: 'Interface languages',
      stat_flow: 'Clean demo flow',
      home_content_tag: 'Content',
      home_content_title: 'Clear layout, easy to read, no clutter.',
      content_card_1_title: 'Fake login / register',
      content_card_1_desc: 'All logic runs in client-side JavaScript, ideal for learning demos and quick testing.',
      content_card_2_title: 'User data management',
      content_card_2_desc: 'Form data is stored so Settings can display and edit it later.',
      content_card_3_title: 'Copy-ready prompt output',
      content_card_3_desc: 'Results are presented cleanly with a copy button for immediate reuse.',
      home_tools_tag: 'Tools',
      home_tools_title: 'Three practical prompt tools for study, code, and work.',
      home_tools_link: 'Go to Tools',
      mini_tool_1_title: 'Study prompt',
      mini_tool_1_desc: 'Build prompts by subject, grade, and output goal.',
      mini_tool_2_title: 'Code prompt',
      mini_tool_2_desc: 'Short, sharp, and effective for real coding requests.',
      mini_tool_3_title: 'Work prompt',
      mini_tool_3_desc: 'Great for tasks, planning, notes, and time management.',
      home_settings_tag: 'Settings',
      home_settings_title: 'Demo profile, language, and personal tweaks.',
      home_settings_link: 'Open Settings',
      settings_preview_label: 'Data synced from the login form',
      settings_preview_pill: 'Editable in the demo UI',
      home_contact_tag: 'Contact',
      home_contact_title: 'A tidy contact area with space for your links later.',
      home_contact_link: 'Open Contact',
      contact_spot_title: 'Social links',
      contact_spot_desc: 'All links are placeholders that you can replace later.',
      contact_spot_title_2: 'Learning support',
      contact_spot_desc_2: 'Designed for students, self-learners, and small teams.',
      chat_tag: 'Mini chatbot',
      chat_title: 'Ask quick questions about the website right on the homepage.',
      tools_tag: 'Tools',
      tools_title: 'A practical prompt generator for study, code, and work.',
      tools_desc: 'Each tool uses its own preset to produce clear, concise, ready-to-use output.',
      tool1_title: 'Study prompt generator',
      tool1_subtitle: 'Subject, grade, question, and desired output.',
      label_subject: 'Subject',
      label_question: 'Question to ask',
      label_output: 'Desired output',
      btn_generate_prompt: 'Generate prompt',
      prompt_result: 'Generated prompt',
      btn_copy: 'Copy',
      tool2_title: 'Code prompt generator',
      tool2_subtitle: 'Goal, language, project type, and special requirements.',
      label_language: 'Language',
      label_project_type: 'Project type',
      label_goal: 'Code goal',
      label_special: 'Special requirements',
      tool3_title: 'Work prompt generator',
      tool3_subtitle: 'Tasks, planning, notes, and prioritization.',
      label_task: 'Task description',
      label_deadline: 'Deadline / timing',
      label_output_type: 'Output format',
      settings_tag: 'Settings',
      settings_title: 'Manage demo profile and UI language.',
      settings_desc: 'Information comes from login/register and can be updated right here.',
      edit_profile_title: 'Edit personal information',
      status_ready: 'Ready',
      btn_save_changes: 'Save changes',
      language_title: 'Language',
      language_desc: 'Change the main language of the demo UI.',
      theme_title: 'Display',
      theme_desc: 'Pick light or dark mode. Dark mode is balanced to be easy on the eyes.',
      theme_light: 'Light mode',
      theme_dark: 'Dark mode',
      contact_tag: 'Contact',
      contact_title: 'A professional contact area with room for real links later.',
      contact_desc: 'The layout is designed to feel tidy, trustworthy, and breathable.',
      contact_links_title: 'Quick links',
      contact_info_title: 'Support info',
      contact_hours: 'Response hours',
      contact_cta_title: 'A professional contact page that never feels empty.',
      contact_cta_desc: 'You can replace the social placeholders with real links after deployment.',
      contact_cta_button: 'View profile',
      contact_cta_button2: 'Open tools',
      logout_title: 'Log out',
      logout_desc: 'End the demo session and return to the login screen.',
      btn_logout: 'Log out',
      purpose_optional_note: 'optional',
      login_unknown_account: 'This account is not registered yet, please register to continue',
      login_wrong_password: 'Incorrect password.',
      home_story_pill: 'Main content block',
      home_story_status: 'For intro content',
      home_story_title: 'This is where you can add the website content text.',
      home_story_desc: 'This block is not an input field. It is designed as a static text area so the homepage stays true to its role: introducing the product, guiding usage, and feeling like a real web app.',
      home_story_quote: 'Clear content helps users quickly understand what the site does, where to go next, and which tool to try first.',
      home_card_1_title: 'Simulated login / register',
      home_card_1_desc: 'The client-side flow is realistic enough for learning and testing, with no backend required.',
      home_card_2_title: 'Synced user data',
      home_card_2_desc: 'Registration data is kept in Settings so it can be viewed and edited.',
      home_card_3_title: 'Clear navigation',
      home_card_3_desc: 'The header and footer lead to dedicated pages instead of putting everything in one place.',
      settings_avatar_title: 'Avatar',
      settings_avatar_desc: 'Upload your photo to use as the avatar in the top-right profile area.',
      settings_avatar_button: 'Upload image',
      settings_avatar_remove: 'Remove image',
      settings_avatar_note: 'If no image is uploaded, the system will use an initials-based avatar.'
    }
  };

  function apply(){
    const lang = window.App ? window.App.getLanguage() : 'vi';
    document.documentElement.lang = lang;
    const map = dict[lang] || dict.vi;
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      if(map[key] != null){
        el.textContent = map[key];
      }
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
      const key = el.getAttribute('data-i18n-placeholder');
      if(map[key] != null){
        el.setAttribute('placeholder', map[key]);
      }
    });
    if(window.Components && typeof window.Components.syncLanguagePills === 'function'){
      window.Components.syncLanguagePills();
    }
  }

  window.Language = { apply, dict };

  if(window.App){
    window.App.ready(() => apply());
  } else {
    document.addEventListener('DOMContentLoaded', apply);
  }
})();
